curl localhost:4000/covidStatus/state/bihar
curl localhost:4000/covidStatus/state/Maharashtra
curl localhost:4000/covidStatus/state/Tamil
curl localhost:4000/covidStatus/state/Delhi
curl localhost:4000/covidStatus/state/Gujarat
curl localhost:4000/covidStatus/state/Uttar
curl localhost:4000/covidStatus/state/Telangana
curl localhost:4000/covidStatus/state/Karnataka
curl localhost:4000/covidStatus/state/West
curl localhost:4000/covidStatus/state/Rajasthan
curl localhost:4000/covidStatus/state/Andhra
curl localhost:4000/covidStatus/state/Haryana
curl localhost:4000/covidStatus/state/Madhya
curl localhost:4000/covidStatus/state/Bihar
curl localhost:4000/covidStatus/state/Assam
curl localhost:4000/covidStatus/state/Odisha
curl localhost:4000/covidStatus/state/Jammu
curl localhost:4000/covidStatus/state/Punjab
curl localhost:4000/covidStatus/state/Kerala
curl localhost:4000/covidStatus/state/Unknown
curl localhost:4000/covidStatus/state/Chhattisgarh
curl localhost:4000/covidStatus/state/Uttarakhand
curl localhost:4000/covidStatus/state/Jharkhand
curl localhost:4000/covidStatus/state/Goa
curl localhost:4000/covidStatus/state/Tripura
curl localhost:4000/covidStatus/state/Manipur
curl localhost:4000/covidStatus/state/Himachal
curl localhost:4000/covidStatus/state/Ladakh
curl localhost:4000/covidStatus/state/Puducherry
curl localhost:4000/covidStatus/state/Nagaland
curl localhost:4000/covidStatus/state/Chandigarh
curl localhost:4000/covidStatus/state/Arunachal
curl localhost:4000/covidStatus/state/Dadra
curl localhost:4000/covidStatus/state/Daman
curl localhost:4000/covidStatus/state/Mizoram
curl localhost:4000/covidStatus/state/Andaman
curl localhost:4000/covidStatus/state/Sikkim
curl localhost:4000/covidStatus/state/Meghalaya
curl localhost:4000/covidStatus/state/Lakshadweep